# Generated by Django 3.1 on 2020-08-11 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantActionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PlantAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='plants.plantactiontype')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='plants.plant')),
            ],
        ),
    ]
