# Generated by Django 3.1 on 2020-08-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantaction',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='planttype',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
